In [1]:
import polars as pl

In [2]:
url = "https://gitlab.com/exploit-database/exploitdb/-/raw/main/files_exploits.csv?ref_type=heads"
df = pl.read_csv(url)

In [3]:
df.head()

shape: (5, 17)
┌───────┬────────────┬────────────┬────────────┬───┬─────────┬────────────┬────────────┬───────────┐
│ id    ┆ file       ┆ descriptio ┆ date_publi ┆ … ┆ aliases ┆ screenshot ┆ applicatio ┆ source_ur │
│ ---   ┆ ---        ┆ n          ┆ shed       ┆   ┆ ---     ┆ _url       ┆ n_url      ┆ l         │
│ i64   ┆ str        ┆ ---        ┆ ---        ┆   ┆ str     ┆ ---        ┆ ---        ┆ ---       │
│       ┆            ┆ str        ┆ str        ┆   ┆         ┆ str        ┆ str        ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═════════╪════════════╪════════════╪═══════════╡
│ 16929 ┆ exploits/a ┆ AIX        ┆ 2010-11-11 ┆ … ┆ null    ┆ null       ┆ null       ┆ http://ai │
│       ┆ ix/dos/169 ┆ Calendar   ┆            ┆   ┆         ┆            ┆            ┆ x.softwar │
│       ┆ 29.rb      ┆ Manager    ┆            ┆   ┆         ┆            ┆            ┆ e.ibm.com │
│       ┆            ┆ Service D… ┆            ┆   ┆         ┆            ┆            ┆ /ai…      │
│ 19046 ┆ exploits/a ┆ AppleShare ┆ 1999-10-15 ┆ … ┆ null    ┆ null       ┆ null       ┆ https://w │
│       ┆ ix/dos/190 ┆ IP Mail    ┆            ┆   ┆         ┆            ┆            ┆ ww.securi │
│       ┆ 46.txt     ┆ Server     ┆            ┆   ┆         ┆            ┆            ┆ tyfocus.c │
│       ┆            ┆ 5.0.…      ┆            ┆   ┆         ┆            ┆            ┆ om/…      │
│ 19049 ┆ exploits/a ┆ BSDI 4.0   ┆ 1998-04-07 ┆ … ┆ null    ┆ null       ┆ null       ┆ https://w │
│       ┆ ix/dos/190 ┆ tcpmux /   ┆            ┆   ┆         ┆            ┆            ┆ ww.securi │
│       ┆ 49.txt     ┆ inetd -    ┆            ┆   ┆         ┆            ┆            ┆ tyfocus.c │
│       ┆            ┆ Cras…      ┆            ┆   ┆         ┆            ┆            ┆ om/…      │
│ 33943 ┆ exploits/a ┆ Flussonic  ┆ 2014-07-01 ┆ … ┆ null    ┆ null       ┆ null       ┆ null      │
│       ┆ ix/dos/339 ┆ Media      ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ 43.txt     ┆ Server     ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆            ┆ 4.1.25 …   ┆            ┆   ┆         ┆            ┆            ┆           │
│ 19418 ┆ exploits/a ┆ IBM AIX    ┆ 1999-07-12 ┆ … ┆ null    ┆ null       ┆ null       ┆ https://w │
│       ┆ ix/dos/194 ┆ 4.3.1 -    ┆            ┆   ┆         ┆            ┆            ┆ ww.securi │
│       ┆ 18.txt     ┆ 'adb'      ┆            ┆   ┆         ┆            ┆            ┆ tyfocus.c │
│       ┆            ┆ Denial o…  ┆            ┆   ┆         ┆            ┆            ┆ om/…      │
└───────┴────────────┴────────────┴────────────┴───┴─────────┴────────────┴────────────┴───────────┘

In [10]:
import re

# 处理codes列：优先匹配CVE编号，如果没有CVE编号，就用OSVDB编号。如果为空字符串，使用file代替
def process_codes(codes, file_path):
    if not codes or codes == "":
        # 如果codes为空，使用file路径作为标识符
        return file_path

    # 优先匹配CVE编号
    cve_match = re.search(r'CVE-\d{4}-\d+', codes)
    if cve_match:
        return cve_match.group(0)

    # 如果没有CVE编号，匹配OSVDB编号
    osvdb_match = re.search(r'OSVDB-\d+', codes)
    if osvdb_match:
        return osvdb_match.group(0)

    # 如果都没有匹配到，返回原始codes
    return codes

# 处理file列：提取文件名的数字，并拼接为exploit-db URL
def process_file(file_path):
    # 使用正则表达式提取路径中的数字
    match = re.search(r'/(\d+)\.', file_path)
    if match:
        exploit_id = match.group(1)
        return f"https://www.exploit-db.com/exploits/{exploit_id}"
    return file_path

# 应用转换 - 使用struct来同时访问多个列
df_processed = df.with_columns([
    pl.struct(["codes", "file"]).map_elements(
        lambda x: process_codes(x["codes"], x["file"]),
        return_dtype=pl.Utf8
    ).alias("cve_id"),
    pl.col("description").alias("description"),  # 保留description
    pl.col("file").map_elements(process_file, return_dtype=pl.Utf8).alias("github_url")
])

# 显示处理结果
df_processed.head()

shape: (5, 19)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id    ┆ file       ┆ descriptio ┆ date_publi ┆ … ┆ applicati ┆ source_ur ┆ cve_id    ┆ github_ur │
│ ---   ┆ ---        ┆ n          ┆ shed       ┆   ┆ on_url    ┆ l         ┆ ---       ┆ l         │
│ i64   ┆ str        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│       ┆            ┆ str        ┆ str        ┆   ┆ str       ┆ str       ┆           ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 16929 ┆ exploits/a ┆ AIX        ┆ 2010-11-11 ┆ … ┆ null      ┆ http://ai ┆ CVE-2009- ┆ https://w │
│       ┆ ix/dos/169 ┆ Calendar   ┆            ┆   ┆           ┆ x.softwar ┆ 3699      ┆ ww.exploi │
│       ┆ 29.rb      ┆ Manager    ┆            ┆   ┆           ┆ e.ibm.com ┆           ┆ t-db.com/ │
│       ┆            ┆ Service D… ┆            ┆   ┆           ┆ /ai…      ┆           ┆ exp…      │
│ 19046 ┆ exploits/a ┆ AppleShare ┆ 1999-10-15 ┆ … ┆ null      ┆ https://w ┆ CVE-1999- ┆ https://w │
│       ┆ ix/dos/190 ┆ IP Mail    ┆            ┆   ┆           ┆ ww.securi ┆ 1015      ┆ ww.exploi │
│       ┆ 46.txt     ┆ Server     ┆            ┆   ┆           ┆ tyfocus.c ┆           ┆ t-db.com/ │
│       ┆            ┆ 5.0.…      ┆            ┆   ┆           ┆ om/…      ┆           ┆ exp…      │
│ 19049 ┆ exploits/a ┆ BSDI 4.0   ┆ 1998-04-07 ┆ … ┆ null      ┆ https://w ┆ OSVDB-828 ┆ https://w │
│       ┆ ix/dos/190 ┆ tcpmux /   ┆            ┆   ┆           ┆ ww.securi ┆ 89        ┆ ww.exploi │
│       ┆ 49.txt     ┆ inetd -    ┆            ┆   ┆           ┆ tyfocus.c ┆           ┆ t-db.com/ │
│       ┆            ┆ Cras…      ┆            ┆   ┆           ┆ om/…      ┆           ┆ exp…      │
│ 33943 ┆ exploits/a ┆ Flussonic  ┆ 2014-07-01 ┆ … ┆ null      ┆ null      ┆ OSVDB-108 ┆ https://w │
│       ┆ ix/dos/339 ┆ Media      ┆            ┆   ┆           ┆           ┆ 610       ┆ ww.exploi │
│       ┆ 43.txt     ┆ Server     ┆            ┆   ┆           ┆           ┆           ┆ t-db.com/ │
│       ┆            ┆ 4.1.25 …   ┆            ┆   ┆           ┆           ┆           ┆ exp…      │
│ 19418 ┆ exploits/a ┆ IBM AIX    ┆ 1999-07-12 ┆ … ┆ null      ┆ https://w ┆ OSVDB-834 ┆ https://w │
│       ┆ ix/dos/194 ┆ 4.3.1 -    ┆            ┆   ┆           ┆ ww.securi ┆ 55        ┆ ww.exploi │
│       ┆ 18.txt     ┆ 'adb'      ┆            ┆   ┆           ┆ tyfocus.c ┆           ┆ t-db.com/ │
│       ┆            ┆ Denial o…  ┆            ┆   ┆           ┆ om/…      ┆           ┆ exp…      │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
len(df_processed)  # 查看处理后的数据行数

46942

In [11]:
# 查询 cve_id 和 github_url是否重复
df_processed.select([
    pl.col("cve_id"),
    pl.col("github_url"),
    pl.count().alias("count")
]).group_by(["cve_id", "github_url"]).agg([
    pl.count().alias("count")
]).filter(pl.col("count") > 1).sort(pl.col("count"))

/tmp/ipykernel_269240/2496911895.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("count")
/tmp/ipykernel_269240/2496911895.py:7: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("count")

shape: (461, 3)
┌─────────────────────────────────┬─────────────────────────────────┬───────┐
│ cve_id                          ┆ github_url                      ┆ count │
│ ---                             ┆ ---                             ┆ ---   │
│ str                             ┆ str                             ┆ u32   │
╞═════════════════════════════════╪═════════════════════════════════╪═══════╡
│ CVE-2018-9445                   ┆ https://www.exploit-db.com/exp… ┆ 2     │
│ exploits/windows/local/46962.p… ┆ https://www.exploit-db.com/exp… ┆ 2     │
│ exploits/windows/dos/46845.py   ┆ https://www.exploit-db.com/exp… ┆ 2     │
│ OVE-20160718-0003               ┆ https://www.exploit-db.com/exp… ┆ 2     │
│ CVE-2017-2476                   ┆ https://www.exploit-db.com/exp… ┆ 2     │
│ …                               ┆ …                               ┆ …     │
│ CVE-2018-8736                   ┆ https://www.exploit-db.com/exp… ┆ 3     │
│ OSVDB-120224                    ┆ https://www.exploit-db.com/exp… ┆ 3     │
│ OVE-20170126-0002               ┆ https://www.exploit-db.com/exp… ┆ 3     │
│ CVE-2015-7243                   ┆ https://www.exploit-db.com/exp… ┆ 3     │
│ CVE-2019-9670                   ┆ https://www.exploit-db.com/exp… ┆ 4     │
└─────────────────────────────────┴─────────────────────────────────┴───────┘